### ISSUE TITLE
Are warnings too verbose by default for end users?

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#42] opened 2014-12-12 15:03 UTC
```
/home/bjwebb/code/opencontracting/flattening-ocds/flattening_ocds/input.py:199: UserWarning: Non-integer value "notanint" found in integer column, returning as string instead.
  warn('Non-integer value "{}" found in integer column, returning as string instead.'.format(value))
/home/bjwebb/code/opencontracting/flattening-ocds/flattening_ocds/input.py:193: UserWarning: Non-numeric value "notanumber" found in number column, returning as string instead.
  warn('Non-numeric value "{}" found in number column, returning as string instead.'.format(value))
```

(from https://gist.github.com/Bjwebb/d41b8efc71e24f5fba16)

Perhaps only the message itself should be printed by default, and not the information of what line the warning was raised on (as most users don't care about this). A verbose or debug command line flag could be added for users who do want the full output.

**Comment by jpmckinney** [comment] 2018-10-18 18:54
I can't reproduce, even if I omit `--root-list-path` or `-s`:

```bash
curl -O https://gist.githubusercontent.com/Bjwebb/d41b8efc71e24f5fba16/raw/eba0ddf3a24a4f8db8c8bc63884956430fa4eb11/error.json
flatten-tool flatten -s path/to/release-schema.json --root-list-path releases error.json
```

Anyhow, can be fixed by overriding `warnings.formatwarning` ([example](https://github.com/open-contracting/standard-maintenance-scripts/blob/master/tests/test_json.py#L94-L98)).

**Closed** 2018-11-21 13:08 UTC
