### ISSUE TITLE
Wrong columns names for spanish OCDS schema

### ISSUE THREAD

**Issue by nativaldezt** [OpenDataServices/flatten-tool#380] opened 2021-02-19 16:31 UTC
When generating the xls template, there are columns that are not with the title that they should, for example, buyer should be as "Comprador" but instead all the data referring to the buyer are with "Referencia de la organización" (en: organization reference):
![image](https://user-images.githubusercontent.com/72802235/108530887-d3525480-72b4-11eb-9240-8ce3ce4df435.png)

Before when it worked well it generated like this:
![image](https://user-images.githubusercontent.com/72802235/108531046-0563b680-72b5-11eb-87f3-3029f8b124c2.png)
This happens for many columns.

The command:
flatten-tool create-template --use-titles -s  https://standard.open-contracting.org/latest/es/release-schema.json -r ocid -m releases --no-deprecated-fields --truncation-length 5

It looks like it is taking the name of the data type instead of the title
![image](https://user-images.githubusercontent.com/72802235/108531676-b8341480-72b5-11eb-984c-03fdb0403eef.png)

**Comment by nativaldezt** [comment] 2021-02-19 16:40
Actually, it is not a problem with the spanish scheme but with the **--use-titles** option, the same thing happens with the english scheme.

**Comment by jpmckinney** [comment] 2021-02-19 16:52
Hmm, this code should have done it. Not sure what caused the regression:

https://github.com/OpenDataServices/flatten-tool/blob/83a4ef21b7a4a482b659e9bb10761cbdd7729f6c/flattentool/schema.py#L255-L261

**Comment by jpmckinney** [comment] 2021-02-19 16:52
What version of flatten-tool are you using (according to `pip list`)?

**Comment by nativaldezt** [comment] 2021-02-19 17:24
Oh, now I realize that I am on the _master_ branch and it must be the _main_ branch, right? 
If the _master_ branch doesn't even exist, how is it that I was in it?
I changed to _main_ and it generated the template well, sorry, it was just that, sad :(

**Comment by nativaldezt** [comment] 2021-02-19 17:42
So, James, I just move to another directory and create a new virtualenv, I did:
pip install flattentool
pip install ocdskit
flatten-tool create-template --use-titles -s  https://standard.open-contracting.org/latest/es/release-schema.json -r ocid -m releases --no-deprecated-fields
and it generated the template with the wrong column names...

**Comment by nativaldezt** [comment] 2021-02-19 17:44
pip list
![image](https://user-images.githubusercontent.com/72802235/108541170-e79c4e80-72c0-11eb-88b8-ffd7c740fab6.png)

**Comment by jpmckinney** [comment] 2021-02-19 18:49
Oh, ha, it's because I fixed it in an unreleased version (#368 was merged in #369): https://github.com/OpenDataServices/flatten-tool/blob/main/CHANGELOG.md#unreleased

So, you'll need to install from GitHub:

```
pip install -e git+https://github.com/opendataservices/flatten-tool.git#egg=flattentool
```

OpenDataServices changed all their "master" branches to "main" (reasons here https://github.com/github/renaming/). OCP will do the same (https://github.com/open-contracting/standard-maintenance-scripts/issues/158).

**Comment by jpmckinney** [comment] 2021-02-19 18:49
@Bjwebb Can you make a release of flatten-tool?

**Comment by Bjwebb** [comment] 2021-02-23 16:43
0.15.3 released https://pypi.org/project/flattentool/#history

**Closed by Bjwebb** 2021-02-23 16:43 UTC
