### ISSUE TITLE
Translation support: Use (truncated) titles for sheet names

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/flatten-tool#306] opened 2019-05-21 18:48 UTC
… and CSV filenames. This can either be the default behavior of `--use-titles`, or an additional flag.

**Comment by robredpath** [comment] 2020-07-28 09:56
![](https://github.trello.services/images/mini-trello-icon.png) [Flatten Tool: Support translation of sheet names](https://trello.com/c/m5zFMCSy/233-flatten-tool-support-translation-of-sheet-names)

**Comment by Bjwebb** [comment] 2020-07-28 10:12
Here's where we define `sub_sheet_name` which become the sheet name or CSV filename: https://github.com/OpenDataServices/flatten-tool/blob/5a9a25f91a84a84c9c9e72381900a20679c3d9a3/flattentool/schema.py#L289

**Comment by yolile** [comment] 2020-08-06 17:37
this should also apply for filenames when generating CSV files

**Comment by Bjwebb** [comment] 2020-08-20 15:18
How does this look? [sample_data_es.xlsx](https://github.com/OpenDataServices/flatten-tool/files/5103929/sample_data_es.xlsx)
(based on converting the sample-data fictional-example)

**Comment by Bjwebb** [comment] 2020-09-03 15:40
@jpmckinney Could you check that spreadsheet looks as you'd expect?

The implementation code here was fairly quick to write, but there's lots to update in the tests.

**Comment by jpmckinney** [comment] 2020-09-04 18:37
Looks good, thanks!

**Comment by Bjwebb** [comment] 2020-09-09 15:38
This is now the default behaviour of `--use-titles`, as I think its reasonable to expect `--use-titles` to use titles in the sheet names, as well as everywhere else.

This work is now merged, and released onto PyPI. Its not yet in CoVE, as I understand this is primarily an issue about CLI usage, but will be added soon along with another change that is in progress.

**Comment by yolile** [comment] 2020-09-17 18:09
I was using this with Colombia data and it fails without further output if a field is not defined in the schema:
![image](https://user-images.githubusercontent.com/6834122/93509500-d1dbc500-f8ed-11ea-886e-278d829a594a.png)

example data to test: https://apiocds.colombiacompra.gov.co:8443/apiCCE2.0/rest/releases/page/2020?page=1

**Comment by Bjwebb** [comment] 2020-09-18 14:25
Thanks, I'm able to reproduce this.

I'm off for the next week, so won't be able to look at this until a week on Monday. The old behaviour is possible by getting an old release off git or PyPI.

**Comment by Bjwebb** [comment] 2020-09-18 14:26
![](https://github.trello.services/images/mini-trello-icon.png) [Fix my recent use titles for sheet names work](https://trello.com/c/2hxuJ3mU/261-fix-my-recent-use-titles-for-sheet-names-work)

**Comment by Bjwebb** [comment] 2020-09-28 17:14
I've fixed this in a PR https://github.com/OpenDataServices/flatten-tool/pull/361, @yolile if you want you can pull that branch to test it. That example data works for me now.

The fix should make its way into a release over the next couple of days.

**Comment by Bjwebb** [comment] 2020-09-29 11:54
The fix is in the latest PyPI release now.

**Closed by Bjwebb** 2020-09-29 11:54 UTC
Labels: OCDS, enhancement
